== congocc-website

A static website dedicated to all things CongoCC, including the parser
generators, multiple programming language parsing, an updated FreeMarker
template system, and more.

Currently, the congocc-website is being developed to use
Asciidoc-formatted text files and JBake to generate the static web pages
displayed on this website. Stay tuned and check congocc.org for the
latest information.

=== Technical Details

JBake expects to find the Asciidoc files to convert into web pages in
folders inside the "content" folder. However, if desired, the default
location for the input files/folders can be overridden on the jbake
command line.

JBake expects to send the generated web pages to a default folder named
"output". This folder will contain all the files necessary display the
website. The default output folder can also be overridden on the jbake
command line.

JBake will be initialized to use FreeMarker templates to generate the
files for the website. The resulting website will be formatted very
similarly to the jbake.org website which in turn is very similar to the
formatting used by AsciiDoctor-pdf, which converts Asciidoc files into
pdf files.

JBake uses default properties to control many behaviors. These defaults
can be overridden in a user's properties file. Setting the archives
property to true causes an archive file to be generated that lists the
dates of all of the blogs in chronological order. The archive page can
be accessed thru the navigation bar/menu bar. Setting the tags property
to true causes a separate page to be generated that groups and lists
each blog by its tag(s). This is page is NOT currently integrated into
the default website. The author and date of any article is listed in its
header but NOT identified by jbakexxxx properties but the date IS
recognized.

==== Some JBake Options

....
jbake -i        initializes a JBake installation
jbake -b        "bakes" all of the pages into a website
jbake -s        "serves" the content. jbake watches the designated content folder(s) and bakes ALL of the files any time a change is detected. The site.host property can be set to a port on localhost to preview the baked output. These baked files can then be uploaded to the docroot location for the website.
....

==== Some JBake Requirements

JBake requires a "header" section that includes: author, date,
jbake-type, jbake-tags, jbake-status. These should go on separate lines
WITHOUT blank lines separating them. Blank lines cause JBake to NOT be
recognize the asciidoc as a web page/post and to NOT generate any html
output.

JBake also requires that the assets, output, and template directories be
located in the same directory as the content directory (which contains
the asciidoc pages/posts). This requirement means that .gitignore file
must be updated so it properly ignores any folders that shouldn't be
included in the repository. And because .gitignore is also tracked under
git, any time it is updated, it needs to get pushed to the repository.

Currently, .gitignore is set to include the templates folders so any
changes to them will be kept in the repository. And the assets folder is
also being included in the repository because I had to rename the
Bootstrap.js & .css files because Chrome kept replacing them with latest
version and screwing up the formatting. Eventually we'll replace these
bootstrap-related files with later versions of them so we'll have to
include them in repository anyway. Shouldn't be an issue since together
they are are less than 1MB in size.

==== Bootstrap

The bootstrap.js library provided with JBake was last updated in 2014
(v3.1.1) and the current release is 5.1-ish. Significant capabilities
have been added (a photo carousel, accordions, and a variety of other
components, svg icons, etc). Need to see if we can update JBake to use
latest version of Bootstrap. During testing, the baked appearance of
webpages showed differently in Chrome and Edge than in Firefox which
seemed to be caused by Chrome recognizing that Bootstrap files were
woefully out of date and kept replacing them with the latest versions
which isn't compatible with older version. By renaming the bootstrap
files to myBootstrap... Chrome was prevented from making these
unrequested substitutions.

==== jQuery

The jQuery.js library included with JBake is version 1.11.1 while the
current version is 3.6.0. Not sure what changes have happened since
v1.11.1 was released but it's probably been a while and one would assume
that numerous safety & security fixes have been included.

[[prettifyjs]]
==== prettify.js

The prettify.js library is also included JBake and is probably also
pretty out of date. I don't see a version in provided .js but the latest
version is 3.1.10.

==== Using Conditionals to Control Output Types

Ideally, the same Asciidoc files will perform multiple roles: blog text
and pdf tech documentation. Conditional directives in Asciidoc allow you
to control which text is displayed/outputted, depending on the
attributes defined.

==== AsciiDoc Conditionals

AsciiDoc can use ifdef . . . endif and ifndef . . . endif conditional
statements to delimit blocks of text to include or exclude from an
outputted document. Here's a few rules.

===== Define Custom Attributes

Surround the custom attribute with single colons. For example

....
:myattribute:
....

===== Use Custom Attributes

To use this custom attribute

....
"ifdef::myattribute[]
The conditional text goes in here and can continue as long as you want until the end block delimiter (endif::[] is reached
endif::myattribute[]"
....

IMPORTANT: Ignore the quotation marks in the above example - the AsciiDoc 
formatter was interpreting (and NOT displaying) the conditionals so NONE 
of the three lines above were shown.

The capitalization of the attribute in the ifdef statement doesn't have
to match its capitalization when it was defined but for tidiness it
probably should match.

In the endif terminator, the name of the attribute is optional - the
most recent ifdef statement is normally used.

You can define a custom attribute and then "turn it off" by inserting
the bang symbol at the beginning of the attribute as follows

....
:!myTurnedOffAttribute:
....

This way you can have the custom attribute ready for use but turned off
so you don't see the conditional text until you want it. Preliminary
testing indicates that the jBake header info can be included at the top
of a text file inside a ifdef::jbake[] conditional block but omitted
from PDF by using the bang to turn off the jbake attribute.

AsciiDoc also includes the ifndef conditional for "if NOT defined"
situations. It works pretty much the same way but the reverse of ifdef.
Any ifndef blocks must be delimited with endif as well.

ifdefs can also call out more than one attribute. For example, if you
were working on a project with multiple versions, you could specify
blocks that applied to just versions 1 or version 3, etc, by combining
them on same ifdef line. You can also specify their relationship (AND,
OR, etc). See AsciiDoc docs for more info on how to do this.

===== Selecting Output for Either Blog or PDF

The PDF books that have been produced so far have all begun with a
"master page" that defines the book settings, title, table of contents,
pagination, etc, as well as the chapters to include. Most importantly,
the book title MUST begin with single "=" to mark it as the highest
level in the book.

The JBake web pages are expected to be more or less stand alone docs and
REQUIRE a title for the post or page that is marked with a single "=" as
the highest level on that post/page.

The Book Title is unhappy if any of its subsections are also marked with
a title ("="). The web pages are unhappy if they don't begin with a
title.

What worked was to define a custom attribute in the PDF book master
page, such as:

....
:pdf-doc:
....

And then down inside each web page to include in the book:

....
"ifdef::pdf-doc[]

== Chapter title or === section title

endif::[]"

"ifndef::pdf-doc[]
= Post or Page Title

. . . . restof JBake header

endif::[]"
....

IMPORTANT: Ignore the quotation marks in the above example - the AsciiDoc 
formatter was interpreting (and NOT displaying) the conditionals so only 
two of the seven above lines were shown.

So when you generate the pdf, it sees the definition of pdf-doc and uses
the correct level of indenture for the Chapter or Section titles and
ignores the JBake header info. And when you are in JBake, it doesn't see
the pdf-doc attribute definition so it ignores the Chapter/section
titles and uses the JBake header info, including the top level title.

So some of the fun stuff in the blog, such as scandalous accusations or
serious fun-making can be marked as ifndef::pdf-doc[] blocks and they
won't show up in the more serious book material. And in the same way,
the section/subsection titles and levels of indenture can be marked
ifdef::pdf-doc[] so they only show up in the book.

== Recommended Combined Template for Articles

----
//global comments and references about this doc can go here
"ifdef::pdf-book[]
== PDF Chapter Title Goes Here
:imagesdir: ../<doc type - learning or blog>/<year>/img
endif::pdf-book[]"
"ifndef::pdf-book[]
= Blog Heading
<Author Name>
<date>
:jbake-type: post
:jbake-tags: learning
:jbake-status: published
== First Level Indent for Blog
:imagesdir: ./img
endif::[]"
----

IMPORTANT:  The quotation marks in the above block are only there so the asciidoc processor won't try to honor the ifdef/ifndef directives, even though they are part of a code/verbatim block

IMPORTANT:  The first level heading (one equals sign level) absolutely must be the first line inside the ifndef block or jbake won't processes the file. ALSO, jbake interprets a blank line as terminating the header block, so name or date or any of the other jbake settings that appear below the blank line will be ignored.

IMPORTANT:  asciidoc *PROHIBITS* a first level heading anywhere but in the master doc but jBake *REQUIRES* a first level heading for every blog page.

asciidoc, asciidoctor, and asciidoctor-pdf all assume that a first level heading is the book title which can only appear ONCE, in the master doc. However, jbake REQUIRES a first level heading or it won't process the doc into an html page.

Therefore, it is necessary to use the ifdef/ifndef block to define the highest level indent for each type. Because these are different levels, it is best to "normalize the headings" by including a second level heading for the blog inside the ifndef block. That way, any additional headers for your text will automatically be at the same level, whether it is in the blog or in the PDF. If you skip the second level blog heading inside the ifndef block, you will have to put ifdef & ifndef blocks around every sub-heading within your doc so they'll be processed correctly. For example, if your blog contains a second level heading (==), when it is processed as a PDF it will be interpreted as a new chapter.

=== JBake notes:

*   the author name field must be filled in or it won't get "baked" into an html page
*   the date is NOT required but the blogs are ordered by date so it is best to include one. The date should be in the format YYYY-MM-DD or it may not be interpreted correctly
*   *_jbake-type_* can be either "post" or "page". They have separate templates and will be processed differently, according to their template.
*   *_jbake-tag_* is optional but is recommended. The tags are used to generate separate pages for each tag. Eventually those tag pages will be used as "category" pages so someone who wants to see pages that are tagged "parsing" or "roadmap" or whatever will see just those pages. I think spelling is critical so a typo will create a different category.
*   *_jbake-status_* can be either "draft" or "published". 
**  *published*: the document is processed into an html page and appears on the website. 
**  *draft*: the document is processed into an html page but it has "draft-" inserted into the filename *AND* to not be displayed on the website. 
**  any other status is undefined

=== Images for Blogs and PDFs

IMPORTANT:  Every document must define the correct imagesdir setting for *both* the PDF (ifdef pdf-book) and the website (ifndef pdf-book)

The imagesdir directive must be set correctly for BOTH types of documents inside the ifdef blocks:

*   PDF Docs:
**  ../<type of doc - learning or blog><year>/img
*   Website Docs:
**  ./img

The reason for these different settings is because the relative paths are handled differently by the processing tools. 

*   asciidoctor-pdf uses the location of the (master) document to be processed as the "root" for its image path
*   jBake uses the location of the file being processed as the "root" for its image page

==== asciidoctor-pdf

Currently, CongoCC is set up to use congocc-website/content/pdf/CongoCCmasterDoc.adoc as the master doc. Inside the master document is a list of every file to be included in the generated PDF. Each included file has its own path specified. Because these included documents will be in a variety of places (learning vs blog, 2022 vs 2023, etc), is ruled out. Instead each document that will go inside the final PDF must include its own imagesdir setting.

==== jBake Website

When jBake runs, it creates or update the output folder that contains the learning and blog folders (as well as all the other infrastructure folders). Under those folders will be the year(s) folder(s) which contains all of the documents for that year as well as the img folder for the documents produced for that year.

==== Image Locations

It could have been setup so there was a single folder for images but this would have created a chaotic maintenance nightmare down the road. It could have also been setup so there was only one imagesdir directive but that would require that we manually duplicate all of the images from their blog/learing image folder locations *OR* we would have had to use absolute paths either in the imagesdir directive OR each image reference would have to include the full absolute path to each image. Either option would have caused all sorts of grief if the contents or images folders got changed.

Finally, the img folder inside the assets folder is copied by jBake to the docroot/img folder. It makes sense to use the assets/img folder for global website images, such as the carousel images that are used in the main page header. Other global images would also appear in here, for example, a custom flourish that was used as a section divider in EVERY doc, it would go here. If an image was only used in a single doc, it wouldn't go here. However, an image that was used for every page (or at least many pages), it would go into the assets/img folder.