//why isn't JBake rendering these diagrams?? Turn off JBake for right now
:pdf-book:
ifndef::pdf-book[]
= Diagrams in AsciiDoc
Nelson Chamberlain
2022-05-06
:jbake-type: post
:jbake-tags: jbake
:jbake-status: published
endif::[]

These diagrams are most easily live previewed using AsciidocFX editor.

== DITAA Block Diagram

Block diagrams rendered in plain text characters on screen

[ditaa, target="asciidoc-diagram", format=png]

....
      +--------------+         +------------+
      |              |         |  output    |
      |  this is a   |-------->|   img      |
      |  diagram     |         |            |
      +----+---------+         +------------+
           |                         ^
           |    lots of work         |
           +----------+--------------+
                      |
                      |
                      |
                      v
            /---------------------\
            |                     |
            |       another       |  Rounded corners
            |         box         |  on this block
            |                     |
            \---------------------/
....

The ditaa declaration block defines the type of the doc, the target (the name of the output file), and the format (png or svg).

== PlantUml Diagram

UML diagrams rendered from declarations in text

[plantuml, target=diagram-classes, format=svg]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

== Syntrax Diagram

Railroad diagrams rendered by jsyntrax using Groovy-based specification language (line(), loop(), stack(), etc). Same target and format options as before.

[syntrax, target=railroad-diagram, format=png]
....
jsyntrax(opt('A', 'B', 'C'));
....

[syntrax, target=indentstack-diagram, format=png]
....
jsyntrax(indentstack(10,
  line(opt('-'), choice('0', line('1-9', loop(None, '0-9'))),
    opt('.', loop('0-9', None))),
  line(opt(choice('e', 'E'), choice(None, '+', '-'), loop('0-9', None)))
));
....

So far I have only been able to get these diagrams to render using the following commands, either:
 
----
asciidoctor -r asciidoctor-diagram <asciidoc-with-diagram-filename>
----

or

----
asciidoctor-diagram <asciidoc-with-diagram-filename>
----

I didn't have any luck generating these diagrams using JBake but I didn't try very hard because they aren't the most important thing to get done right now.