:!jbake:
ifdef::jbake[]
= Learning JBake - Part 2
Nelson Chamberlain
2022-05-05
:jbake-type: post
:jbake-tags: jbake
:jbake-status: draft
endif::[]

ifndef::jbake[]
= Notes and Comments on JBake - 2
endif::[]

== Using JBake and congocc-website Repository Locally
When you clone the congocc website from github, the repository is automatically put into a folder named congocc-website. I think this folder name can be changed without causing problems, but that's another issue. For right now, the default folder name is good enough. 

Select a good location on your *local computer* for the repository. It will need to be conveniently accessible to both JBake and your chosen Asciidoc editor. On my local comuter, I have JBAKE_HOME set to D:\jbake and all congocc related stuff on D:\congocc. Inside congocc folder, I cloned the repository as follows:

----
git clone https://github.com/congo-cc/congocc-website.git
----

When the repository is cloned, you end up with the same three folders that are created when you initialize JBake (jbake -i command):

*   assets - contains folders for css, fonts, img, and js. The complete contents of all the subfolders are tracked/managed in the repository rather than trying to separate the modified and unmodified files
*   content - contains all of the asciidoc files that are baked into the website
*   templates - contains all the FreeMarker templates that are used to generate the components of the web pages (header, footer, etc). All of the templates are tracked/managed in the repository rather than trying to manage the modified and unmodified files

The jbake.properties file is also cloned into your repository folder, just like in the initialized JBake layout. In other words, the repository should have the same folder structure and contents as a newly initialized JBake installation, except that for the updates that were saved to the repository.

The cloned repository also adds two files:

*   README.md - contains lots of info about using JBake and using conditionals in asciidocs to produce different outputs (websites vs pdfs). 
*   .gitignore - a hidden file that contains a list of folders and/or files that should NOT be tracked/managed in the repository.

=== The .gitignore File

On my local computer, in the congocc-website folder, I created a folder named saved that holds the bits and pieces that I might or might not use going forward. Since these items might never get used in the website, there's no point in having them tracked in the web. So .gitignore lists the saved/ folder so its contents won't end up in the repository unless they are actually used in the website.

When JBake actually bakes the website, the default location for the .html and other files is the output folder. Since these files are regenerated every time jbake -b is run, there's no point in tracking/managing these files in the repository, especially since JBake overwrites all of the output files every time it bakes the website, which would cause every one of the website pages to be updated in the master website, even if there was no other change than their file dates.

JBake has an option to run its database tool, orientdb, in either the memory mode or in the persistent mode. The default mode is memory mode and *nothing* needs to be set to achieve this mode. The mode can be set to persist by adding db.store=plocal to the jbake.properties file. If orientdb is set to persist (non-memory) then a new folder named cache will be added to the repository folder. Since the persistent mode stores transient data in the cache folder that has no long term value, this folder is also listed in .gitignore. There doesn't seem to be any issues with telling git to ignore non-existent folders.

If you add other folders to the congocc-website that you don't want to save in the repository, be sure to add the folder to .gitignore. If you *do* want to save the files to the repository but you don't want them published on the website, either don't add the JBake header lines to those files or use a custom attribute to surround the header lines so that the files aren't baked. See below on the section on header lines, custom attributes, and conditionals.

=== The .jbakeignore File

JBake reserves the filename of .jbakeignore for use in controlling what files/folders are rendered/copied the the website. Unfortunately, it is NOT a list of files/folders to skip; instead it is a flag that is used to mark which folders to NOT render/bake. Its usage is as follows:

*   contents folder or subfolders: any source files that appear in the same folder as the .jbakeignore file (or subfolders below it) are skipped.
*   assets folder or subfolders: any resources that appear in the same folder as the .jbakeignore file (or subfolders below it) are not copied to the site (apparently used for rendering but NOT copied to output folder to be used by website).
*   any other folders that contain .jbakeignore have the flag file ignored

=== Bringing It All Together Locally

So after cloning the congocc-website repository, a git status command should show that everything is up to date. Point your asciidoc editor to a file that you want to add or update in the assets, content, or templates folders and make the necessary changes or additions. 

After saving the changes, if you repeat the git status command, it should list any files that you have modified or added. It all should work like working on any files (code, web, template) that are part of a repository. 

When changes have been made to tracked files, you should bake your website to verify that the changes are achieving the effects that you want. You can use the jbake -b command to rebuild the website and then view the files in the file manager *OR* you can use the jbake -b -s command to rebuild the website and then view the website at http://localhost:8820. 

When a reasonable amount or set of changes have been made and tested, the changes should be committed and pushed up to the repository, just like working on any other repository.

== JBake and the Website Repository on the Server

JBake has been installed in ~/nelson/jbake and JBAKE_HOME has been set in his profile. JBake hasn't been added to his path yet because it's been easy enough to just call the bin/jbake shell script from JBAKE_HOME. The jbake - i and jbake -b commands have both been successfully run and their results match the locally generated files and results.

I tried jbake -b -s but was unable to reach congocc.org:8820 with a browser. I suspect the firewall app needs to be told to allow web serving at port 8820 because that's where Jetty wants to serve it. It could also be that ubuntu doesn't like the "localhost" setting used by JBake. 

I suspect a better process than using Jetty would be to set up a subdomain like testing.congocc.org and then copy any generated files to the subdomain and then serve them from the docroot there. What would be even slicker would be if the testing docroot could be set to ~/nelson/jbake/congocc-website/output so it would automatically serve the most recently baked website files. 

=== JBake and Repository Runs

The congocc-website repository was cloned into ~/nelson/jbake/congocc-website and jbake -b was run and it seemed to work fine. Used nano to open a few of the files in the output folder and got the expected results.

Did `cd output` and then changed the ownership of the files in the output folder using:

----
sudo chown -R root:root .
----

Then copied the output folder to docroot of congcc.org using:

----
sudo cp -R . /var/www/html
----

Copy (cp) overwrites existing files automatically so there was no need to use a command to force the overwriting. The congocc.org website is now serving the latest version of the files from the repository. The easiest way to verify that was to verify that the RSS menu option was removed from the navigation bar. Used FireFox and Chrome to view congocc.org and both contain the correct contents

Just used my iPhone and Safari to access congocc.org and it seemed to work OK. The nav bar was collapsed into a button at top right. Tapping on the button brought up the menu options.

=== Production Setup

Based on current understanding, the setup will be something like:

.   JBake and congocc-website repository will need to be setup someplace accessible by the root user and JBake put onto its path. 
.   Users will clone the congocc-website repository to their local computer and push any changes/additions to the repository using normal git procedures
.   A website update process will get run, triggered either by repository change being detected or based on time that includes:
..  Getting latest contents of the congocc-website repository
..  Running JBake against the copy of the repository
..  Getting the contents of the output folder copied to /var/www/html

WARNING: Setting the destination.folder in the jbake.properties file doesn't seem to work. A brief reading of the JBake source shows that it uses a org.apache.commons.configuration.compositeConfigure which uses an "anti-inheritance" pattern; the first definition of a property added to the compositeConfig is the one that is used; any later settings to that property are NOT used. *IF* jbake.properties file is added second then user settings would never get set. Other things work - it is inconceivable that this is the problem. And yet, setting the destination.folder doesn't seem to work!!

Until the website get's huge, it might be simplest to just run JBake once a day, whether or not any changes have been made. JBake works on a similar principle; it 'bakes' every file every time it runs, whether or not the files have been changed. 

== JBake Header Lines, Custom Attributes, and Conditionals

Asciidocs require JBake header lines in every file that is going to be baked for the website. ALL lines in the JBake header must be together - no blank lines are allowed or JBake will assume this is NOT a valid header and will NOT produce any output.

----
:!jbake: <1>
ifdef::jbake[] <2>
= Learning JBake - Part 2 <3>
Nelson Chamberlain <4>
2022-05-05 <5>
:jbake-type: post <6>
:jbake-tags: jbake <7>
:jbake-status: draft <8>
endif::[] <9>

ifndef::jbake[] <10>
= Notes and Comments on JBake - 2 <11>
endif::[] <12>
----
<1> custom attribute defined in this file. In this definition, jbake is also 'inactivated' by the bang symbol.
<2> if jbake attribute was defined, then the following header lines would have been 'visible'. JBake would then have seen this document as one that needed to be 'baked' and converted it into an html file 
<3> JBake requires a top level heading (single '=' level) to be used as the post/page title. If it doesn't see this, it won't bake the file into an html page
<4> Author's name. I don't know how it recognizes this as a name without associating it with an attribute.
<5> the desired publication date
<6> custom JBake attribute. Legal values are post and page
<7> custom JBake attribute. Comma separated list of tags to associate with this page. Each item in list will produce an html page associated with that tag. If multiple asciidocs include that tag, they will all be listed on that html page.
<8> custom JBake attribute. Legal values are draft and published.
<9> endif for the ifdef above. The name of the ifdef value can optionally be included between the double colons and the square brackets
<10> If-NOT-Defined. Reciprocal of the ifdef block above. This will be more useful when we are producing pdf docs because those want to have the top level (single '=' level) value set for the book title and NOT the page title and asciidoctor-pdf will complain/fail if it finds a 'book title' value in one of the other files. Note also that since this line isn't part of the JBake header lines it can have a blank line above it.
<11> Added a title just for some content. If we were producing a pdf book using this file, this would need to be a '==' or lower level heading or asciidoctor-pdf will complain.
<12> Closing endif for the ifndef. Attribute name is optional but can be included between the double-colons and the square brackets.
